- hosts: k8s_cluster
  roles:
    - role: kafka
      vars: 
        type_exec: "{{ type_exec | default('deploy') }}"
    - role: flink
      vars: 
        type_exec: "{{ type_exec | default('deploy') }}"