- name: Ensure Helm is installed
  apt:
    name: helm
    state: present
  become: true

- name: Add the Prometheus Helm repository
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

- name: Update Helm repositories
  command: helm repo update

- block:
    - name: Install Prometheus using the official chart
      command: helm install prometheus prometheus-community/prometheus \
        --namespace prometheus --create-namespace \
        --set server.service.type=NodePort

  when: type_exec == 'deploy'

- block:
    - name: Uninstall Prometheus
      command: helm uninstall prometheus -n prometheus

  when: type_exec == 'delete'
